# Generated by Django 4.1.13 on 2024-09-12 19:16

import WebProject.utils.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(2, message='Nickname must be at least 2 chars long!')])),
                ('first_name', models.CharField(max_length=30, validators=[WebProject.utils.validators.validate_name_starts_with_capital], verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, validators=[WebProject.utils.validators.validate_name_starts_with_capital], verbose_name='Last Name')),
                ('chef', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
